### ISSUE TITLE
Buggy download of virtualbox.box file is disabling 'vagrant up' process

### ISSUE THREAD

**Issue by answerquest** [laidig/vagrant-gtfs-editor#1]
Hi, I'm trying to get this running on my system. The server from where the download is happening seems to be very slow and keeps erroring out. I'm trying repeatedly since 2 days now. Pasting most recent terminal output:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-14.04-i386' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/ubuntu-14.04-i386'
    default: URL: https://vagrantcloud.com/bento/ubuntu-14.04-i386
==> default: Adding box 'bento/ubuntu-14.04-i386' (v201802.02.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-14.04-i386/versions/201802.02.0/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
    default: Progress: 36% (Rate: 0/s, Estimated time remaining: 0:12:44)

```
The download keeps getting stalled midway and goes down to 0/s in some time. And even when it's working, the speed is much lower than what my internet can do.
I copied the link: `https://vagrantcloud.com/bento/boxes/ubuntu-14.04-i386/versions/201802.02.0/providers/virtualbox.box` and downloaded it separately with aria2c which experienced drops and reconnected and got it downloaded. It's now sitting as a gzip archive with this name: `9b0e5aa7-1eb8-4cfe-a666-80908629a761` . I tried opening it and it errored out.

I'm not even sure if a valid copy of the file has been downloaded. And if it has, then please guide as to what to do next: 
I put the file into the cloned repo folder, typed `vagrant up` again. It didn't detect the file and tried to download it again. I also understand that there are other automated things to happen after the download and if the chain is broken then I don't know what more to do here.

Can someone guide on how to get this thing running? Or, are there alternatives? Also, I just want to check this out, some screenshots of how the interface and all is would be wonderful. Does this allow full-fledged GTFS editing including timings?

**Comment by laidig** [comment]
you can try the official Ubuntu 14.04 box by changing config.vm.box in Vagrantfile to ubuntu/trusty32. If that doesn't work, let me know and I'll give it a shot tomorrow.

**Comment by laidig** [comment]
Did this help you?

**Comment by answerquest** [comment]
Hi @laidig , apologies for not getting back earlier. Since I don't understand all the terminology, and also because my machine doesn't meet the RAM requirements which I noticed later, I decided to abandon the pursuit. Anyways with this much complexity i don't think i can get the agency to run this.
