### ISSUE TITLE
Updating gtfs-editor to the last version of datatools

### ISSUE THREAD

**Issue by mlumeau** [laidig/vagrant-gtfs-editor#2]
Hi, do you have any plans to update to the last version of [datatools-ui](https://github.com/catalogueglobal/datatools-ui) and [datatools-server](https://github.com/conveyal/datatools-server)? 
As far as I know, gtfs-editor is now deprecated but your solution still remains the most simple way to deploy conveyal's gtfs tools.

**Comment by laidig** [comment]
Hi there,

I haven't thought of making a similar package for datatools, but I
understand why you would want to-- there are a lot of moving parts. I won't
have time to do so until late June at the earliest, maybe then I will try.

I did contribute a docker setup for
https://github.com/WRI-Cities/static-GTFS-manager , which is another
recently released GTFS editor.

**Comment by mlumeau** [comment]
Thank you for considerating that.
I'll check out your other solution in the meantime.
